name: Unzip and Build APK
on:
  workflow_dispatch:

jobs:
  unzip_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip project
        run: |
          unzip -o TruckingApp-starter.zip -d .
          if [ -d "TruckingApp" ]; then
            shopt -s dotglob
            # Move everything EXCEPT .github (to avoid conflict)
            mv TruckingApp/* .
            if [ -d "TruckingApp/.github" ]; then
              echo "Skipping .github from inside zip"
            fi
            rmdir TruckingApp || true
          fi
          echo "After unzip:"
          ls -la

      - name: Patch Kotlin version (root build.gradle.kts)
        run: |
          if [ -f build.gradle.kts ]; then
            sed -i 's/id("org.jetbrains.kotlin.android") version "2.0.20"/id("org.jetbrains.kotlin.android") version "1.9.24"/' build.gradle.kts
          fi
          echo "Using Kotlin version:"
          grep 'org.jetbrains.kotlin.android' build.gradle.kts || true

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Debug APK
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7
          arguments: assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
