name: Unzip and Build APK
on:
  workflow_dispatch:

jobs:
  unzip_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo contents (before unzip)
        run: ls -la

      - name: Unzip project and move contents (skip .github)
        shell: bash
        run: |
          set -euxo pipefail
          unzip -o TruckingApp-starter.zip -d .
          # If the ZIP has a top-level TruckingApp/ folder, move its children up,
          # but DO NOT move .github to avoid conflicts with workflows in the repo.
          if [ -d "TruckingApp" ]; then
            shopt -s dotglob
            for p in TruckingApp/*; do
              base="$(basename "$p")"
              if [ "$base" = ".github" ]; then
                echo "Skipping $p"
                continue
              fi
              mv "$p" .
            done
            rmdir TruckingApp || true
          fi
          echo "After unzip / move:"
          ls -la
          echo "Tree (top level):"
          ls -la .

      - name: Verify Gradle files exist
        run: |
          test -f settings.gradle.kts && echo "Found settings.gradle.kts" || (echo "Missing settings.gradle.kts" && exit 1)
          test -f build.gradle.kts && echo "Found root build.gradle.kts" || (echo "Missing root build.gradle.kts" && exit 1)
          test -f app/build.gradle.kts && echo "Found app/build.gradle.kts" || (echo "Missing app/build.gradle.kts" && exit 1)

      - name: Show current Kotlin/Compose versions
        run: |
          echo "Root build.gradle.kts (plugins):"
          grep -n 'org.jetbrains.kotlin.android' -n build.gradle.kts || true
          echo "App composeOptions in app/build.gradle.kts:"
          grep -n 'kotlinCompilerExtensionVersion' app/build.gradle.kts || true

      # ---- Auto-fix Kotlin/Compose mismatch (downgrade Kotlin to 1.9.24) ----
      - name: Patch Kotlin version (root build.gradle.kts)
        run: |
          set -euxo pipefail
          # Replace ANY 2.0.x with 1.9.24
          sed -i 's/id("org.jetbrains.kotlin.android") version "2\.0\.[0-9]\+"/id("org.jetbrains.kotlin.android") version "1.9.24"/' build.gradle.kts
          echo "After patch:"
          grep -n 'org.jetbrains.kotlin.android' build.gradle.kts

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Optional: generate Gradle wrapper so future steps can use ./gradlew
      - name: Generate Gradle wrapper (optional)
        run: |
          gradle -v
          gradle wrapper
          ./gradlew -v
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: Build Debug APK
        # Prefer using the wrapper if present; fall back to the action
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
